### ISSUE TITLE
在某些sql中，数据库支持函数条件，where对于字符串都加上了‘’

### ISSUE THREAD

**Issue by KiVirgil** [golyu/sql-build#3]
在某些数据库中，指出一些函数操作，如我想取某一时间段的数据:
select service, operation from permission where tid > toTimeUUID('2017-10-27 01:00+0000')

使用sql-build:

`sql := sqlBuild.Select("permission ").Column("service", "operation").Where( "toTimeUUID('2017-10-27 01:00+0000')", "tid > ").String()
`
得到的sql是：
select service, operation from permission where tid > 'toTimeUUID('2017-10-27 01:00+0000')'

**Comment by golyu** [comment]
已经解决了,本来想增加函数WhereFunc(...)这种写法的,为了方便之前的写法,现在string类型会自动判断是否是函数,如果是函数,就不会加上''了

**Comment by KiVirgil** [comment]
我看你是判断 ')'是否是在字符串结束，
但是比如influxdb是支持now()函数运算的，这样对于
select service, operation from permission where time > now() - 1h的话，还是加上了''

**Comment by golyu** [comment]
哦,这个样子啊,那就还是加上whereFunc方法,本来判断括号的方式就是有些草率的,因为有的数据里确实可能会出现括号,我稍晚加上,现在在上班
